// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enfgfobivkdhfvnlfxoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuZmdmb2JpdmtkaGZ2bmxmeG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTM4ODgsImV4cCI6MjA3MTE4OTg4OH0.0c6dNsCzjQ7tV4dALaC1vKUeivbMT9FfoLy3w4brA-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});