// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jejwzqxgrxnphbbvtdqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impland6cXhncnhucGhiYnZ0ZHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MDU0MzUsImV4cCI6MjA5MTM4MTQzNX0.T3QCQ2aKpMI0IzJpA3ekBGes7UD_JSchQJZH7ADeATg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});